---
kind: Service
apiVersion: v1
metadata:
  name: rucio-server-cms
spec:
  selector:
    run: rucio-server-cms

# All the ports that are open in the container. Label correctly as we figure out what they are
  ports:
  - name: rucio1
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
  - name: rucio2
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: rucio3
    protocol: TCP
    port: 80
    targetPort: 80
  - name: rucio4
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30880
  - name: supervisord
    protocol: TCP
    port: 8088
    targetPort: 8088
    nodePort: 30888
  type: NodePort
...

---
kind: Service
apiVersion: v1
metadata:
  name: rucio-graphite
spec:
  selector:
    run: rucio-graphite

# Just some for now, rest are not needed?
  ports:
  - name: graphite
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31080
  - port: 8125
    name: statsd
    protocol: UDP
  - port: 8126
    name: admin
    protocol: TCP
  type: NodePort
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-server-cms
  labels:
    run: rucio-server-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rucio-server-cms
  template:
    metadata:
      labels:
        run: rucio-server-cms
    spec:

    # Main container containing all the Rucio stuff
      containers:
      - name: rucio-server-cms
        image: cmssw/rucio_server_cms
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8443
        - containerPort: 8080
        - containerPort: 8088
        # Environment variable wtih the DB connect string (Oracle, Postgres, etc)
        env:
        - name: DBURL
          valueFrom:
            secretKeyRef:
              name: dburl
              key: DBURL.txt
        # Openstack gives us the cert and key for the host, so mount them
        volumeMounts:
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true

      # Openstack gives us the cert and key for the host, so mount them
      volumes:
      - name: hostkey
        hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
      - name: hostcert
        hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-graphite
  labels:
    run: rucio-graphite
spec:
  replicas: 1

  selector:
    matchLabels:
      run: rucio-graphite
  template:
    metadata:
      labels:
        run: rucio-graphite
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    # Main container containing all the Rucio stuff
      containers:
      # Graphite server
      - name: rucio-graphite
        image: graphiteapp/graphite-statsd
        securityContext:
          privileged: false
        ports:
        - containerPort: 80
        - containerPort: 2003
        - containerPort: 2004
        - containerPort: 2023
        - containerPort: 2024
        - containerPort: 8125
          protocol: UDP
          name: statsd
        - containerPort: 8126
          name: admin
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-client
  labels:
    run: rucio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rucio-client
  template:
    metadata:
      labels:
        run: rucio-client
    spec:

    # A client for testing
      containers:
      - name: rucio-client
        image: cmssw/rucio_client
        securityContext:
          privileged: false
        volumeMounts:
        - name: globus
          mountPath: /root/.globus/
          readOnly: true
      volumes:
      - name: globus
        secret:
          secretName: globus
          defaultMode: 256
...
