apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rucio-consistency.fullname" . }}-tmp-deckard
  labels:
    {{- include "rucio-consistency.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: 1
{{- end }}
  selector:
    matchLabels:
      {{- include "rucio-consistency.selectorLabels" . | nindent 6 }}
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/jobberConfig: {{ include (print $.Template.BasePath "/tmp-deckard-jobber-configmap.yaml") . | sha256sum }}
        checksum/deckardConfig: {{ include (print $.Template.BasePath "/tmp-deckard-configmap.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rucio-consistency.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deckard.image.repository }}:{{ .Values.deckard.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUCIO_CFG_COMMON_LOGLEVEL
              valueFrom:
                secretKeyRef:
                  key: common_loglevel
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_DEFAULT
              valueFrom:
                secretKeyRef:
                  key: database_default
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_ECHO
              valueFrom:
                secretKeyRef:
                  key: database_echo
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_MAX_OVERFLOW
              valueFrom:
                secretKeyRef:
                  key: database_max_overflow
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_POOL_RECYCLE
              valueFrom:
                secretKeyRef:
                  key: database_pool_recycle
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_POOL_RESET_ON_RETURN
              valueFrom:
                secretKeyRef:
                  key: database_pool_reset_on_return
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  key: database_pool_size
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_CFG_DATABASE_POOL_TIMEOUT
              valueFrom:
                secretKeyRef:
                  key: database_pool_timeout
                  name: cms-ruciod-{{ .Values.consistency.instance }}-rucio-daemons.cfg
            - name: RUCIO_DAEMON
              value: deckard
            - name: RUCIO_CFG_POLICY_LFN2PFN_MODULE
              value: cmstfc
            - name: RUCIO_HOME
              value: /opt/rucio

          command: ["/deckard/deckard_run.sh"]
          resources:
            {{- toYaml .Values.deckard.resources | nindent 12 }}
          #        readinesProbe:
          #          exec:
          #            command:
          #              - /sync-live-check.sh
          #          initialDelaySeconds: 5
          #          periodSeconds: 15
          #        livenessProbe:
          #          exec:
          #            command:
          #              - /sync-live-check.sh
          #          initialDelaySeconds: 60
          #          periodSeconds: 60
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config/
              name: deckard-config
            - mountPath: /etc/jobber-config/
              name: jobber-config
            - mountPath: /opt/proxy
              name: proxy-volume
            - mountPath: /etc/grid-security/certificates
              name: ca-volume
            - mountPath: /var/cache/consistency-dump
              name: consistency-dump
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: consistency-dump
        persistentVolumeClaim:
            claimName: {{ .Release.Name }}-report-pvc
      - name: proxy-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-{{ .Values.consistency.instance }}-rucio-x509up
      - name: ca-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-{{ .Values.consistency.instance }}-rucio-ca-bundle
      - name: jobber-config
        configMap:
          defaultMode: 0644
          name: {{ include "rucio-consistency.fullname" . }}-tmp-deckard-jobber-config
      - name: deckard-config
        configMap:
          defaultMode: 0644
          name: {{ include "rucio-consistency.fullname" . }}-tmp-deckard-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
