image:
  repository: cmssw/rucio-daemons

abacusAccountCount: 1
abacusRseCount: 1
#conveyorTransferSubmitterCount: 2
conveyorTransferSubmitterCount: 3
conveyorPollerCount: 2
conveyorFinisherCount: 2
conveyorStagerCount: 0
hermesCount: 1
judgeCleanerCount: 1
judgeEvaluatorCount: 1
judgeInjectorCount: 1
judgeRepairerCount: 1
tracerKronosCount: 1
transmogrifierCount: 1
undertakerCount: 1
reaperCount: 0
reaper2Count: 1
minosCount: 1
necromancerCount: 1
darkReaperCount: 1

darkReaper:
  includeRses: "T1_ES_PIC_Disk"

abacusRse:
  threads: 2
  resources:
    limits:
      cpu: 700m
      memory: 4000Mi
    requests:
      cpu: 700m
      memory: 900Mi

reaper2:
  greedy: 0
  threads: 8
  resources:
    requests:
      memory: 750Mi
    limits:
      memory: 2Gi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

conveyorTransferSubmitter:
  activities: "'Data Consolidation' 'Recovery' 'Data Brokering' 'Data rebalancing' 'Debug' 'Express' 'Functional Test' 'Group Subscriptions' 'Production Input' 'Production Output' 'Analysis Input' 'Analysis Output' 'Staging' 'T0 Export' 'T0 Tape' 'Upload/Download (Job)' 'Upload/Download (User)' 'User Subscriptions'"
    # Same size or smaller than bulk which is 100
  groupBulk: 50
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

conveyorFinisher:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

conveyorPoller:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

# Settings to renew FTS	proxy
ftsRenewal:
  enabled: 1
  image:
    repository: rucio/fts-cron
    tag: latest
  voms: "cms:/cms/Role=production"
  servers: "https://fts3-devel.cern.ch:8446,https://cmsfts3.fnal.gov:8446,https://fts3-cms.cern.ch:8446,https://lcgfts3.gridpp.rl.ac.uk:8446,https://fts3-pilot.cern.ch:8446"

hermes:
  useSSL: 1
  threads: 5
  bulk: 500
  brokerTimeout: 120
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  resources:
    requests:
      memory: 400Mi
    limits:
      memory: 600Mi

judgeEvaluator: 
  resources:
    limits:
      cpu: 3750m 
    requests:
      cpu: 750m 
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

judgeCleaner:
  threads: 2
  resources:
    limits:
      cpu: 3750m 
      memory: 4000Mi
    requests:
      cpu: 750m 
      memory: 400Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

judgeInjector:
  threads: 2
  resources:
    limits:
      cpu: 3750m 
      memory: 8000Mi
    requests:
      cpu: 750m 
      memory: 400Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

judgeRepairer:
  resources:
    limits:
      cpu: 3750m 
      memory: 4000Mi
    requests:
      cpu: 750m 
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

monitoring:
  enabled: true
  serviceMonitorEnabled: false

config:
    common:
        loglevel: "INFO"
    messaging_hermes:
        port: "61323"
        brokers: "cms-mb.cern.ch"
        ssl_key_file: "/opt/rucio/keys/new_userkey.pem"
        ssl_cert_file: "/opt/rucio/certs/usercert.pem"
        destination: "/topic/cms.rucio.events"
        voname: "cms"
    monitor:
      enable_metrics: "True"
      metrics_port: "8080"
    tracer_kronos:
        username: "cmsrucio"
        port: "61313"
        brokers: "cms-mb.cern.ch"
        queue: "/queue/Consumer.kronos.cms.rucio.tracer"
        # FIXME: Both used to be 50 before 1.24 problems with Kronos
        chunksize: "1"
        prefetch_size: "10"

transmogrifier:
  threads: 4
  bulk: 100
  resources:
    requests:
      memory: 200Mi
    limits:
      memory: 1450Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

tracerKronos:
  # FIXME: Was 5 before 1.24 problems with Kronos
  threads: 1
  resources:
    limits:
      cpu: 3000m 
      memory: 1Gi
    requests:
      cpu: 1000m 
      memory: 800Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

abacusAccount:
    resources:
      limits:
        cpu: 700m
        memory: 2000Mi
      requests:
        cpu: 700m
        memory: 250Mi

# Unused daemons which supply prometheus
automatix:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

conveyorReceiver:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

conveyorThrottler:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

minos:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

necromancer:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

undertaker:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

