ingress:
  hosts: 
    - cms-rucio-test.cern.ch
hermes:
    useSSL: 1
config:
    messaging_hermes:
        port: "61323"
        brokers: "cms-mb.cern.ch"
        ssl_key_file: "/opt/rucio/keys/new_userkey.pem"
        ssl_cert_file: "/opt/rucio/certs/usercert.pem"
        destination: "/topic/cms.rucio.events"
        voname: "cms"
