persistence:
  enabled: false
service:
  type: NodePort

filters:
  main: |-
    filter {
      drop { }
    }


outputs:
  main: |-
    output {
      # Send message in JSON form to CERN monit
      http {
        http_method => "post"
        id => "monit_http_output"
        url => "http://monit-logs.cern.ch:10012/"
        format => "json"
      }
    }
