kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: int-rucio-consistency-ceph   
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: meyrin-cephfs 

