apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-cms-consistency
  labels:
    app: rucio-cms-consistency
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rucio-cms-consistency
      release: cms-sync-int
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rucio-cms-consistency
        release: cms-sync-int
    spec:
      containers:
      - env:
        - name: RUCIO_CFG_COMMON_LOGLEVEL
          valueFrom:
            secretKeyRef:
              key: common_loglevel
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_DEFAULT
          valueFrom:
            secretKeyRef:
              key: database_default
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_ECHO
          valueFrom:
            secretKeyRef:
              key: database_echo
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_MAX_OVERFLOW
          valueFrom:
            secretKeyRef:
              key: database_max_overflow
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_RECYCLE
          valueFrom:
            secretKeyRef:
              key: database_pool_recycle
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_RESET_ON_RETURN
          valueFrom:
            secretKeyRef:
              key: database_pool_reset_on_return
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_SIZE
          valueFrom:
            secretKeyRef:
              key: database_pool_size
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_TIMEOUT
          valueFrom:
            secretKeyRef:
              key: database_pool_timeout
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_CARBON_SERVER
          valueFrom:
            secretKeyRef:
              key: monitor_carbon_server
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_USER_SCOPE
          valueFrom:
            secretKeyRef:
              key: monitor_user_scope
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_LFN2PFN_ALGORITHM_DEFAULT
          valueFrom:
            secretKeyRef:
              key: policy_lfn2pfn_algorithm_default
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_LFN2PFN_MODULE
          valueFrom:
            secretKeyRef:
              key: policy_lfn2pfn_module
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_PERMISSION
          valueFrom:
            secretKeyRef:
              key: policy_permission
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_SCHEMA
          valueFrom:
            secretKeyRef:
              key: policy_schema
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_SUPPORT
          valueFrom:
            secretKeyRef:
              key: policy_support
              name: cms-ruciod-int-rucio-daemons.cfg
        image: cmssw/rucio-consistency:latest
        imagePullPolicy: Always
        name: cms-rucio-consistency
        command: ["/consistency/run.sh"]
#        args: ["infinity"]
        resources:
          limits:
            memory: 3000Mi
            ephemeral-storage: 20Gi
          requests:
            cpu: 1800m
            memory: 2000Mi
            ephemeral-storage: 20Gi
#        readinesProbe:
#          exec:
#            command:
#              - /sync-live-check.sh
#          initialDelaySeconds: 5
#          periodSeconds: 15
#        livenessProbe:
#          exec:
#            command:
#              - /sync-live-check.sh
#          initialDelaySeconds: 60
#          periodSeconds: 60
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/
          name: consistency-config
        - mountPath: /etc/jobber-config/
          name: jobber-config
        - mountPath: /opt/proxy
          name: proxy-volume
        - mountPath: /opt/certs
          name: ca-volume
        - mountPath: /var/cache/consistency-dump
          name: consistency-dump
        - mountPath: /var/cache/consistency-temp
          name: csi-data-cinderplugin
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: csi-data-cinderplugin
        persistentVolumeClaim:
          claimName: int-rucio-consistency-cinder
          readOnly: false
      - name: consistency-dump
        persistentVolumeClaim:
            claimName: int-rucio-consistency-ceph
      - name: proxy-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-int-rucio-x509up
      - name: ca-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-int-rucio-ca-bundle
      - name: jobber-config
        configMap:
          defaultMode: 0644
          name: jobber-config
      - name: consistency-config
        configMap:
          defaultMode: 0644
          name: consistency-config



