abacusAccountCount: 0
abacusRseCount: 0
conveyorStagerCount: 0
hermesCount: 0
judgeCleanerCount: 0
judgeEvaluatorCount: 0
judgeInjectorCount: 0
judgeRepairerCount: 0
tracerKronosCount: 0
transmogrifierCount: 0
undertakerCount: 0
reaperCount: 0
reaper2Count: 1
minosCount: 0
necromancerCount: 0



conveyorTransferSubmitterCount: 1
conveyorPreparerCount: 1
conveyorPollerCount: 1
conveyorFinisherCount: 1

ftsRenewal:
  enabled: 0


podLabels:
  rucioInstance: "int"

config:
    common:
        loglevel: "DEBUG"
        #loglevel: "INFO"
    conveyor:
      use_preparer: "True"
      scheme: "globus"
      transfertool: "globus"
      filter_transfertool: "globus"
      transfertype: bulk
      globus_auth_app: CMSRucioProduction

conveyorTransferSubmitter:
  activities: "'User Subscriptions'"
    # Same size or smaller than bulk which is 100
  threads: 1
  bulk: 50
  groupBulk: 50

reaper2:
  includeRses: "rse=T3_US_Theta"
  scheme: "globus"
  chunk_size: 1
  greedy: 1
  threads: 1
