apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cpio1
provisioner: cinder.csi.openstack.org
parameters:
  type: cpio1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: int-rucio-consistency-cinder
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-sc-cpio1

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpio1
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-cinderplugin
  volumes:
  - name: csi-data-cinderplugin
    persistentVolumeClaim:
      claimName: csi-pvc-cpio1
      readOnly: false

